### ISSUE TITLE
Implement battery saves

### ISSUE THREAD

**Issue by PDJazzHands** [ejona86/taus#22]
Please implement a battery save feature

**Comment by ejona86** [comment]
[Kirjava](https://github.com/kirjavascript) recently made one and shared it on the CTM Discord. [persistent_highscores.zip](https://github.com/ejona86/taus/files/5721317/persistent_highscores.zip) I've not tried it out yet.

**Comment by ejona86** [comment]
CC @kirjavascript

**Comment by kirjavascript** [comment]
While that IPS works fine as a one off hack, I think there are other things I think that should be done before integrating it into a main hack.

Some mechanism for clearing the scores is required - this could be as simple as holding `select` on boot.

SRAM detection might be needed. There are some environments / carts (cheap EEPROMS) that will report that SRAM is working but will just load garbage data instead - which could lead to impossible to beat scores in the list. I'm not sure what the 'correct' way to do this is but perhaps some writes to SRAM and then reads to confirm the data is correct is a sensible approach.

**Comment by ejona86** [comment]
With #23 merged I'm going to close this. While us perfectionists may still want to eek a bit more out of the idea most players should be good with the merged state. The next release will include it, but until then [save-highscores.dist.zip](https://github.com/ejona86/taus/files/5768441/save-highscores.dist.zip). This version should have expanded compatibility with other mods, but is otherwise similar to what I linked to earlier.

**Comment by PDJazzHands** [comment]
thank you!
