### ISSUE TITLE
Highscore initializing not working right on NT Mini Noir

### ISSUE THREAD

**Issue by Stabyourself** [ejona86/taus#25]
When I load the patched rom (either with TAUS+highscore or just highscore alone) using the NT Mini Noir jailbreak 6.5, the highscores are initialized to the following:

![image](https://user-images.githubusercontent.com/1524030/106522185-9417bb80-64df-11eb-8747-2d3f0beb852a.png)

The same rom correctly initializes to an empty state in BizHawk (using NesHawk).

**Comment by ejona86** [comment]
The mod doesn't actually zero-out the save state; it utilized that emulators tend to start with zeroed-out sram. Do you know what save format the NT Mini Noir jailbreak uses? Maybe you can just share your save and I can try hacking it to see if I can initialize it.

CC @kirjavascript

**Comment by kirjavascript** [comment]
we could perhaps set an additional SRAM byte to a magic number, and zero the data out if it isn't set, to circumvent the issue. should still fit in the `defaultHighScores` section

strange that the SRAM isnt zeroed by default though, probably worth looking into that further

**Comment by Stabyourself** [comment]
[Tetris (USA, TAUS).sav.zip](https://github.com/ejona86/taus/files/5911664/Tetris.USA.TAUS.sav.zip)
Here's a save from the system.

It's just FF's

[Legend of Zelda, The (USA) (Rev A).sav.zip](https://github.com/ejona86/taus/files/5911722/Legend.of.Zelda.The.USA.Rev.A.sav.zip)
Just for comparison sake, here's a save from zelda 1

**Comment by ejona86** [comment]
@Stabyourself, try this one: [Tetris (USA, TAUS).zeroed.sav.zip](https://github.com/ejona86/taus/files/5936249/Tetris.USA.TAUS.zeroed.sav.zip) (renaming the file to the original name)

With just FFs means it is just a plain memory dump; no special headers. So I just replaced all the FFs with 00s.

**Comment by Stabyourself** [comment]
Using that save, it started at 000000 for all the scores and I was able to set a score, reload the rom and have my highscore loaded.

Thanks!!

Here's the new save from the system in case you need it:
[Tetris (USA, TAUS).sav.zip](https://github.com/ejona86/taus/files/5936294/Tetris.USA.TAUS.sav.zip)

**Comment by ejona86** [comment]
@kirjavascript, I reworked the save-highscores mod to detect uninitialized SRAM. The cold boot detection logic turned out to be a convenient and spacious place to put code, so I also restored the default high scores.

@Stabyourself, [save-highscores-1.4.1-dev.zip](https://github.com/ejona86/taus/files/6642365/save-highscores-1.4.1-dev.zip) should work for you as an alternative to manually pre-initializing SRAM, not that you need it at this point. However, this new version of the mod will reset your high scores if you use a save from the older mod.
