### ISSUE TITLE
saves highscore doesn't show level in mode B

### ISSUE THREAD

**Issue by yepyepyep4711** [ejona86/taus#29]
As the title says. I have one rom patched with 2player mode, handicap, garbage and saves highscore. In mode B, the level shown to the right of the highscore list is always 00, regardless of the level played.

**Comment by ejona86** [comment]
This is the same issues as you mentioned in https://github.com/ejona86/taus/issues/27#issuecomment-870742558 . It turned out it wasn't showing you "p1 level" but instead the level wasn't being set at all, so it was "the previous level for that high score entry." When using save-highscores that level would be 0 which made the problem more obvious.

This was fixed in 18f9be38073222160bd23d9ec72e88116dd37be7

Thanks for the report!
